version: '3'

services:
  colegiobapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: colegiob-docker
    container_name: colegiobapp
    restart: always # reiniciar el contenedor si se detiene
    ports:
      - '${PORT}:${PORT}'
    networks:
      - colegiob-network
    # working_dir: /var/www/pokedex
    environment:
      PORT: ${PORT}
      DEFAULT_LIMIT: ${DEFAULT_LIMIT}
      JWT_SECRET: ${JWT_SECRET}
    # volumes:
    #   - ./:/var/www/pokedex

networks:
  colegiob-network:
