version: '3'

services:
  db:
    image: mongo:5
    container_name: mongo-colegio
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGODB_DATABASE: colegio-FeyAlegria
    volumes:
      - ./mongo:/data/db
