version: '3'

services:
  colegiobapp:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    image: colegiob-docker
    container_name: colegiobapp
    restart: always # reiniciar el contenedor si se detiene
    ports:
      - '${PORT}:${PORT}'
    # working_dir: /var/www/pokedex
    environment:
      MONGODB: ${MONGODB}
      PORT: ${PORT}
      DEFAULT_LIMIT: ${DEFAULT_LIMIT}
      JWT_SECRET: ${JWT_SECRET}
    # volumes:
    #   - ./:/var/www/pokedex

  db:
    image: mongo:5
    command: mongod --port 27017
    container_name: mongo-colegio
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGODB_DATABASE: colegio-FeyAlegria
    volumes:
      - ./mongo:/data/db